"""
Auto-generate HuggingFace model cards with training config, benchmark results,
dataset info, and hardware details.
"""

from __future__ import annotations

import logging
import platform
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from lfm_trainer.benchmark import BenchmarkComparison, BenchmarkResult
    from lfm_trainer.config import TrainingConfig

logger = logging.getLogger(__name__)


def generate_model_card(
    cfg: TrainingConfig,
    benchmark_results: list[BenchmarkResult | BenchmarkComparison] | None = None,
    training_time_seconds: float | None = None,
) -> str:
    """Generate a HuggingFace model card markdown string.

    Parameters
    ----------
    cfg:
        The training configuration used.
    benchmark_results:
        Optional benchmark results to embed.
    training_time_seconds:
        Total training wall-time in seconds.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # ── YAML frontmatter ──────────────────────────────────────────────
    tags = ["lfm-trainer", "lora", "peft", "code"]
    if cfg.tool_calling_only:
        tags.append("tool-calling")

    base_model = cfg.resume_from_model or cfg.model_name
    repo = cfg.hub_repo_id or "lfm-finetune"

    lines = [
        "---",
        f"base_model: {cfg.model_name}",
        f"tags: {tags}",
        "library_name: peft",
        f"license: mit",
        "---",
        "",
        f"# {repo}",
        "",
        f"Fine-tuned from **{cfg.model_name}** using [lfm-trainer](https://github.com/your-username/llm-training).",
        "",
    ]

    # ── Training details ──────────────────────────────────────────────
    lines.extend([
        "## Training Details",
        "",
        "| Parameter | Value |",
        "|-----------|-------|",
        f"| Base model | `{cfg.model_name}` |",
    ])

    if cfg.resume_from_model:
        lines.append(f"| Resumed from | `{cfg.resume_from_model}` |")

    lines.extend([
        f"| LoRA rank (r) | {cfg.lora_r} |",
        f"| LoRA alpha | {cfg.lora_alpha} |",
        f"| LoRA dropout | {cfg.lora_dropout} |",
        f"| Epochs | {cfg.num_train_epochs} |",
        f"| Batch size | {cfg.per_device_train_batch_size} |",
        f"| Gradient accum. | {cfg.gradient_accumulation_steps} |",
        f"| Learning rate | {cfg.learning_rate} |",
        f"| Max seq length | {cfg.max_seq_length} |",
        f"| Precision | {'bf16' if cfg.bf16 else 'fp16'} |",
        f"| Trained at | {now} |",
    ])

    if training_time_seconds:
        mins = training_time_seconds / 60
        lines.append(f"| Training time | {mins:.1f} min |")

    lines.append("")

    # ── Datasets ──────────────────────────────────────────────────────
    lines.extend([
        "## Datasets",
        "",
    ])
    for ds in cfg.dataset_paths:
        lines.append(f"- `{ds}`")
    if cfg.tool_calling_only:
        lines.append("")
        lines.append("> Filtered to tool-calling examples only.")
    lines.append("")

    # ── Benchmark results ─────────────────────────────────────────────
    if benchmark_results:
        from lfm_trainer.benchmark import format_benchmark_report

        lines.append(format_benchmark_report(benchmark_results))

    # ── Hardware ──────────────────────────────────────────────────────
    try:
        import torch

        if torch.cuda.is_available():
            gpu_name = torch.cuda.get_device_name(0)
            gpu_count = torch.cuda.device_count()
            gpu_mem = torch.cuda.get_device_properties(0).total_mem / 1e9
            lines.extend([
                "## Hardware",
                "",
                f"- **GPU**: {gpu_count}× {gpu_name} ({gpu_mem:.0f} GB each)",
                f"- **Platform**: {platform.system()} {platform.machine()}",
                "",
            ])
    except Exception:
        pass

    # ── Usage ─────────────────────────────────────────────────────────
    lines.extend([
        "## Usage",
        "",
        "```python",
        "from peft import PeftModel",
        "from transformers import AutoModelForCausalLM, AutoTokenizer",
        "",
        f'base = AutoModelForCausalLM.from_pretrained("{cfg.model_name}", trust_remote_code=True)',
        f'model = PeftModel.from_pretrained(base, "{repo}")',
        f'tokenizer = AutoTokenizer.from_pretrained("{repo}")',
        "```",
        "",
        "---",
        f"*Generated by [lfm-trainer](https://github.com/your-username/llm-training) on {now}*",
    ])

    return "\n".join(lines)


def save_model_card(
    cfg: TrainingConfig,
    output_dir: str,
    benchmark_results=None,
    training_time_seconds: float | None = None,
) -> str:
    """Generate and save a model card to the output directory.

    Returns the path to the saved README.md.
    """
    card = generate_model_card(cfg, benchmark_results, training_time_seconds)
    path = f"{output_dir}/README.md"

    with open(path, "w") as f:
        f.write(card)

    logger.info("📄 Model card saved to %s", path)
    return path
